name: emoji_picker
description: A Flutter package that provides an Emoji Keyboard widget with 390 emojis in 8 categories.
version: 0.3.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.3
  scrollable_positioned_list: ^0.1.9
  equatable: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jeffg.emoji_picker
        pluginClass: EmojiPickerPlugin
      ios:
        pluginClass: EmojiPickerPlugin
