name: emoji_picker
description: A Flutter package that provides an Emoji Keyboard widget with 390 emojis in 8 categories.
version: 0.5.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.0
  scrollable_positioned_list: ^0.3.8
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jeffg.emoji_picker
        pluginClass: EmojiPickerPlugin
      ios:
        pluginClass: EmojiPickerPlugin
